---
#
# Ansible managed
#
repository:
  description: The purpose of this role is to restore objects to your system.
  homepage: https://robertdebock.nl/
  topics: restore, server, system, ansible, molecule, tox, playbook, hacktoberfest
