---
- name: test if restore_directory is set correctly
  assert:
    that:
      - restore_directory is defined
    quiet: yes

- name: test if restore_remote_directory is set correctly
  assert:
    that:
      - restore_remote_directory is defined
    quiet: yes

- name: test if restore_mysql_username is set correctly
  assert:
    that:
    quiet: yes
  when:
    - restore_mysql_username is defined

- name: test if restore_mysql_password is set correctly
  assert:
    that:
    quiet: yes
  when:
    - restore_mysql_password is defined

- name: test if restore_objects is set correctly
  assert:
    that:
      - restore_objects is defined
      - restore_objects is iterable
    quiet: yes

- name: test if item in restore_objects is set correctly
  assert:
    that:
      - item.name is defined
      - item.type is defined
      - item.type in [ "directory", "mysql" ]
      - item.destination is defined
    quiet: yes
  loop: "{{ restore_objects }}"
  loop_control:
    label: "{{ item.name }}"
