---
- name: find most recent object
  find:
    paths: "{{ restore_directory }}/{{ inventory_hostname }}"
    patterns: "{{ object.type }}-{{ object.name }}-*"
  register: found_files
  delegate_to: localhost
  become: no

- name: select latest_file in found_files
  set_fact:
    latest_file: "{{ found_files.files | sort(attribute='mtime',reverse=true) | first }}"
  when:
    - found_files.files | length > 0

- name: copy latest_file
  copy:
    src: "{{ latest_file.path }}"
    dest: "{{ restore_remote_directory }}/{{ latest_file.path | basename }}"
  when:
    - latest_file is defined

- name: unarchive directory object
  unarchive:
    src: "{{ latest_file.path }}"
    dest: "{{ object.destination }}"
  when:
    - latest_file is defined
    - object.type == "directory"

- name: find extension
  set_fact:
    latest_file_extension: "{{ latest_file.path | basename | splitext | last }}"
  when:
    - latest_file is defined
    - object.type == "mysql"

- name: unarchive mysql object
  unarchive:
    src: "{{ restore_remote_directory }}/{{ latest_file.path | basename }}"
    dest: "{{ restore_remote_directory }}"
    exclude: "{{ object.exclude | default(omit) }}"
    remote_src: yes
  when:
    - latest_file is defined
    - object.type == "mysql"
    - latest_file_extension in [".gz", ".tgz", ".tar", ".zip"]

- name: import mysql database
  mysql_db:
    name: "{{ object.destination }}"
    target: "{{ restore_remote_directory }}/{{ latest_file.path | basename | splitext | first }}.sql"
    state: import
  when:
    - latest_file is defined
    - object.type == "mysql"
