---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: robertdebock.restore
      restore_mysql_username: restore
      restore_mysql_password: rest0re
      restore_objects:
        - name: home
          type: directory
          destination: /home
        - name: test_db
          type: mysql
          destination: test_db
