---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-mysql
      mysql_databases:
        - name: test_db
          encoding: utf8
          collation: utf8_bin
    - role: ansible-role-backup
      backup_format: tar
      backup_objects:
        - name: home
          type: directory
          source: /home
        - name: test_db
          type: mysql
          source: test_db
          format: zip
    - role: ansible-role-restore
      restore_objects:
        - name: home
          type: directory
          destination: /home
        - name: test_db
          type: mysql
          destination: test_db
