---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: create a directory to backup
      file:
        path: /home/test
        state: directory

  roles:
    - role: robertdebock.mysql
      mysql_databases:
        - name: test_db
          encoding: utf8
          collation: utf8_bin
    - role: robertdebock.backup
      backup_format: zip
      backup_objects:
        - name: home
          type: directory
          source: /home
        - name: test_db
          type: mysql
          source: test_db
          format: zip
    - role: ansible-role-restore
      restore_objects:
        - name: home
          type: directory
          destination: /home
        - name: test_db
          type: mysql
          destination: test_db
