---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: Create a directory to backup
      ansible.builtin.file:
        path: /home/test
        state: directory

  roles:
    - role: robertdebock.mysql
      mysql_databases:
        - name: Test_db
          encoding: utf8
          collation: utf8_bin
      mysql_users:
        - name: Restore
          password: rest0re
          priv: "test_db.*:ALL"
    - role: robertdebock.postgres
      postgres_databases:
        - name: Test_db
          state: present
    - role: robertdebock.backup
      backup_format: zip
      backup_objects:
        - name: Home
          type: directory
          source: /home
        - name: Test_db
          type: mysql
          source: test_db
          format: zip
        - name: Test_db
          type: postgres
          source: test_db
          format: zip
    - role: ansible-role-restore
      restore_mysql_username: restore
      restore_mysql_password: rest0re
      restore_objects:
        - name: Home
          type: directory
          destination: /home
        - name: Test_db
          type: mysql
          destination: test_db
